name: gat
description: "A GAT project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  # Icons
  cupertino_icons: ^1.0.8
  # State Management
  get: ^4.6.6
  gap: ^3.0.1
  flutter_svg:
  pinput:
  dotted_line: ^3.2.3
  flutter_spinkit:
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  percent_indicator: ^4.2.5
  permission_handler:
  firebase_messaging:
  flutter_local_notifications:
  firebase_auth:
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  country_code_picker: ^3.3.0
  web_socket_channel: ^3.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio:
  shimmer: ^3.0.0
  fluttertoast: 8.2.8
  in_app_purchase: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/will_be_delete/





